### ISSUE TITLE
How to predict, using plm()?

### ISSUE THREAD

**Issue by OleksiyAnokhin** [ycroissant/plm#19]
Hi team, thanks for a great package?
I check all possible resources, but do not see how to used `predict()` or `prediction()` with `plm`.

Currently I am trying:

`predictions <- predict(plmFit1, panel_df_test)`

and get

`Error in crossprod(beta, t(X)) : non-conformable arguments`

**Comment by tappek** [comment]
Hi, seems like you were trying to `predict` using a within model. That case what not implemented - until now in this commit b81d759332114e3cafa663fc9217da9f0b8c99e4 in the development version.

Be aware that the within case is somewhat special, more so with out-of-sample prediction. The help page `?predict.plm` has the details and examples.

Feedback is welcome!

To install the development version from GitHub:
```
# install.packages("remotes") # remove '#' if pkg 'remotes' is not installed
remotes::install_github("ycroissant/plm")
```

**Comment by tappek** [comment]
Some reference asking for `predict` for plm objects/fixed effects models (copied from https://github.com/jacob-long/jtools/issues/97#issuecomment-1092403373):

https://github.com/leeper/prediction/issues/19
https://github.com/strengejacke/ggeffects/issues/121
https://stackoverflow.com/questions/31954045/r-plotting-panel-model-predictions-using-plm-pglm
https://stackoverflow.com/questions/64892622/plotting-interaction-terms-from-fixed-effects-models-plm
https://stackoverflow.com/questions/71366468/predict-on-test-data-using-plm-package-in-r-and-calculate-rmse-for-test-data

**Comment by tappek** [comment]
Closing this because it is solved.

**Comment by tappek** [comment]
On CRAN as plm 2.6-2 as of 2022-08-16
