### ISSUE TITLE
Suggestion: use collapse::rsplit/gsplit to speed up other code

### ISSUE THREAD

**Issue by SebKrantz** [ycroissant/plm#33]
Hi Kevin, having {collapse} as a hard dependency provides many opportunities for further drop-in performance improvements, one particularly significant one that came to mind would probably be to use the faster split functions: `rsplit()` being a recursive version of `split()`, that, with arguments `drop = FALSE` and `flatten = TRUE` works just like `split()`. There is also a barebones function called `gsplit()`, which is even faster as it only works for vectors and by default does not save the names. 

``` r
library(collapse)
library(microbenchmark)

v = wlddev$PCGDP
f = wlddev$iso3c
g = GRP(f)

# Vector
microbenchmark(gsplit(v, g), rsplit(v, g), rsplit(v, f), split(v, f))
#> Unit: microseconds
#>          expr     min       lq     mean   median       uq      max neval cld
#>  gsplit(v, g)  85.680 116.0250 151.1944 126.5120 166.6745  537.730   100 a  
#>  rsplit(v, g)  94.160 124.9500 165.5100 136.9995 189.4330  580.123   100 a  
#>  rsplit(v, f) 195.458 227.3640 322.0670 242.9830 270.2040 4041.218   100  b 
#>   split(v, f) 346.289 390.9145 475.0852 403.4090 489.3115 1404.788   100   c

# Data Frame
microbenchmark(rsplit(wlddev, g), rsplit(wlddev, f), split(wlddev, f))
#> Unit: milliseconds
#>               expr       min        lq      mean    median        uq        max neval cld
#>  rsplit(wlddev, g)  1.242354  1.395417  1.999074  1.533084  2.075499  11.572538   100  a 
#>  rsplit(wlddev, f)  1.318662  1.480204  1.915902  1.617872  2.362436   4.278622   100  a 
#>   split(wlddev, f) 36.952416 42.953552 52.031342 50.696393 58.052336 106.491162   100   b
```

<sup>Created on 2022-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SebKrantz** [comment]
Hi Kevin, that's right, `rsplit()` has no matrix method. I could add it for the next release though. The main reason it is not there is because I never required it. The good news is that `gsplit()` has the option to keep the first argument empty (`NULL`), which will return indices that can be used to subset the matrix: 

``` r
library(collapse)

X = qM(mtcars)
f = qF(mtcars$cyl)

X_spl = lapply(gsplit(g = f), function(i) X[i, ])
str(X_spl)
#> List of 3
#>  $ : num [1:11, 1:11] 22.8 24.4 22.8 32.4 30.4 33.9 21.5 27.3 26 30.4 ...
#>   ..- attr(*, "dimnames")=List of 2
#>   .. ..$ : chr [1:11] "Datsun 710" "Merc 240D" "Merc 230" "Fiat 128" ...
#>   .. ..$ : chr [1:11] "mpg" "cyl" "disp" "hp" ...
#>  $ : num [1:7, 1:11] 21 21 21.4 18.1 19.2 17.8 19.7 6 6 6 ...
#>   ..- attr(*, "dimnames")=List of 2
#>   .. ..$ : chr [1:7] "Mazda RX4" "Mazda RX4 Wag" "Hornet 4 Drive" "Valiant" ...
#>   .. ..$ : chr [1:11] "mpg" "cyl" "disp" "hp" ...
#>  $ : num [1:14, 1:11] 18.7 14.3 16.4 17.3 15.2 10.4 10.4 14.7 15.5 15.2 ...
#>   ..- attr(*, "dimnames")=List of 2
#>   .. ..$ : chr [1:14] "Hornet Sportabout" "Duster 360" "Merc 450SE" "Merc 450SL" ...
#>   .. ..$ : chr [1:11] "mpg" "cyl" "disp" "hp" ...
```

<sup>Created on 2022-09-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by SebKrantz** [comment]
Also note that 'GRP' objects are more efficient inputs for all of these functions (factors will be converted to 'GRP' objects). So if you can, use `g = GRP(mtcars$cyl)` instead of `qF(mtcars$cyl)`.

**Comment by tappek** [comment]
A matrix method would be convinied! Shall I file an issue in collpase's repository?

**Comment by SebKrantz** [comment]
A minor update of collapse just hit CRAN, which includes rsplit.matrix. I had to update earlier than planned due to issues with newer C compilers now used on R-devel checks. So you can move ahead with this.

**Comment by SebKrantz** [comment]
It’s ok, I have noted it elsewhere. But may take a while before a new
update lands on CRAN, so perhaps create the method yourself for internal
plm usage using the code I suggest.

**Comment by tappek** [comment]
Hope to have the few remnants of base R's `split()` substituted before long and will then release.

Btw: Since plm 2.6-2, we make already use of `collapse::qtable` (with commit 82092f6).

**Comment by SebKrantz** [comment]
Great, happy to see things moving forward.
