### ISSUE TITLE
automatically handle missing values in pmg

### ISSUE THREAD

**Issue by waynelapierre** [ycroissant/plm#6]
I noticed that I need to remove all missing values when using plm::pmg. Most other econometrics packages can automatically handle missing values. Would you add this feature in the future? Thanks.

**Comment by tappek** [comment]
`pmg` removes observations when NA is encountered. Could you provide an example to illustrate what you have in mind?

**Comment by waynelapierre** [comment]
After updating to the most recent plm, it seems plm can handle missing values in independent and dependent variables now. Does it also handle missing values in the time and id index?

**Comment by tappek** [comment]
Please make sure to use the latest CRAN version before you write in. Please read the NEWS (from 2.4-1):

NAs are "handled" like this (at least currently; One could argue to drop affected rows with a warning):

```
- pdata.frame: warns if NA in index dimension is encountered (before, only a plain message was printed).
- Between/between/Sum/Within: Methods which rely on the index attribute (*.pseries and partly *.matrix) now error informatively if NA in any index dimension is encountered.
```
