### ISSUE TITLE
Stata's 'weakivtest' with plm?

### ISSUE THREAD

**Issue by afmaschke** [ycroissant/plm#8]
Hi,

I was wondering whether plm has a built in command for calculating the 'effective F statistic' for weak instrument tests? In stata, the user-written command 'weakivtest' calculates the effective F, see: https://journals.sagepub.com/doi/pdf/10.1177/1536867X1501500113 

The test was developed by Montiel Olea and Pflueger (2013): https://www.carolinpflueger.com/MOP_FINAL_May14.pdf 

I couldn't find anything related to this test in the vignette, so thought I'd ask here.

Thank you for your time!

**Comment by tappek** [comment]
You did not oversee something: we do not have this test in the package.

**Comment by afmaschke** [comment]
OK, thanks.

**Comment by tappek** [comment]
Did you look for implementations in R in general (I did not)? If there are any, maybe they accept plm`s IV models out of the box or can be modified to accept them.

**Comment by afmaschke** [comment]
Yeah, I've looked around, but couldn't find anything unfortunately. Thanks for the suggestion though.
